### ISSUE TITLE
[BUG] Postgres db authentication errors.

### ISSUE THREAD

**Issue by denverwilliams** [crosscloudci/ci_status_repository#14]
CI jobs for the status repository fail to keep the password state for the postgres db.
This results in the backend using the wrong credentials to connect to the db.

**Comment by denverwilliams** [comment]
The temporary fix for this is to disable db persistence.
https://github.com/crosscloudci/ci_status_repository/commit/f3e49c6b05c8c33531c18bc748a011d68c118d9f

**Comment by agentpoyo** [comment]
Temporary fix in place, unless we want to improve, closing.
